version: '3'
services:
  svelte-compose:
    env_file:
      - ./../env/docker.env
    build:
      context: ./../app
      dockerfile: ./../docker/dockerfile
    ports:
      - "${OUTER_PORT_FRONTEND}:${INNER_PORT_FRONTEND}"
    volumes:
      - ./../app/src/:/app/src/
    command: pnpm dev
