# FROM node:16
FROM node:19-alpine3.16
WORKDIR /app
# Redo this with regex to not include the node_modules folder and cut down number of layers
COPY /src ./src
COPY /tests ./tests
COPY /static ./static
COPY package.json svelte.config.js \
    tsconfig.json playwright.config.ts \
    vite.config.ts entrypoint.sh ./
COPY ./entrypoint.sh ./entrypoint.sh
RUN chmod u+x ./entrypoint.sh
RUN apk add --no-cache bash
RUN npm install -g pnpm && pnpm install && pnpm run build
