# FROM node:16
# FROM node:18-alpine3.16
FROM node:19-alpine3.16
WORKDIR /app
# Redo this with regex to not include the node_modules folder and cut down number of layers
COPY /src ./src
COPY /tests ./tests
COPY /static ./static
COPY entrypoint.sh \
    package.json \
    # package-lock.json \
    pnpm-lock.yaml \
    playwright.config.ts \
    postcss.config.cjs \
    svelte.config.js \
    tailwind.config.cjs \
    tsconfig.json \
    vite.config.ts ./
RUN chmod u+x ./entrypoint.sh
RUN apk add --no-cache bash
# RUN npm install pm2 -g
RUN npm install -g pnpm && pnpm install && pnpm run build
# RUN npm install && npm run build
